### ISSUE TITLE
Other mods accessing TradeOffers causes your mod to crash

### ISSUE THREAD

**Issue by Linguardium** [HyperPigeon/Better-Wandering-Trader#1]
https://github.com/HyperPigeon/Better-Wandering-Trader/blob/cd41702e13e4f6d865bc4669a3a27626ff321bbc/src/main/java/net/hyper_pigeon/better_wandering_trader/mixin/TraderOffersMixin.java#L124
You add a static reference to your autoconfig which may be initialized before your mod does (so your config isnt loaded yet). 
ideally, dont access your config statically in a mixin as you cant guarantee your mod will load first.

you may want to get access to the list and then add to it in your mod rather than the mixin. you could add an accessor for this

**Comment by HyperPigeon** [comment]
Thank you for bringing to my attention. I have taken your advice and there should not be anymore issues with mods that also access TradeOffers.
